on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  a_test_job:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: commits
        env:
          COMMITS: ${{ toJson(github.event.commits) }}
        run: echo "$COMMITS"
      - name: commit messages
        env:
          COMMIT_MESSAGES: ${{ join(toJson(github.event.commits.*.message)) }}
        run: echo "$COMMIT_MESSAGES"
      - name: check if should skip
        env:
          MESSAGES_NOTCONTAINS_SKIP: ${{ !contains(join(toJson(github.event.commits.*.message)), '#skip') }}
        run: echo "$MESSAGES_NOTCONTAINS_SKIP"
      - name: test check
        env:
          MESSAGES_NOTCONTAINS_TOMATO: ${{ !contains(join(toJson(github.event.commits.*.message)), 'tomato') }}
        run: echo "$MESSAGES_NOTCONTAINS_TOMATO"
