on:
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  a_test_job:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: event info
        env:
          EVENTS: ${{ toJson(github.event) }}
        run: echo "$EVENTS"
      - name: number
        env:
          NUMBER: ${{ toJson(github.event.number) }}
        run: echo "$NUMBER"
      - name: commits
        env:
          COMMITS: ${{ github.event.commits }}
        run: echo "$COMMITS"
      - name: commit messages
        env:
          COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
        run: echo "$COMMIT_MESSAGES"
