on:
  schedule:
    - cron: '30 * * * *'

jobs:
  periodic-health-check:
    runs-on: ubuntu-20.04
    steps:
      - name: Perform periodic health check
        uses: Jtalk/url-health-check-action@v4
        with:
          url: https://full-stack-open-pokedex-yaups.fly.dev/periodic-health
